export const data = {
  products: [
    {
      id: 0,
      img: "/images/preview1.png",
      name: "Nike Air Jordan",
      category: "Men Shoes",
      color: "1 Color available",
      price: 100,
    },
    {
      id: 1,
      img: "/images/preview2.png",
      name: "Nike Air Jordan1",
      category: "Men Shoes",
      color: "1 Color available",
      price: 110,
    },
    {
      id: 2,
      img: "/images/preview3.png",
      name: "Nike Air Jordan2",
      category: "Men Shoes",
      color: "1 Color available",
      price: 120,
    },
    {
      id: 3,
      img: "/images/preview4.png",
      name: "Nike Air Jordan3",
      category: "Men Shoes",
      color: "1 Color available",
      price: 130,
    },
    {
      id: 4,
      img: "/images/preview5.png",
      name: "Nike Air Jordan4",
      category: "Men Shoes",
      color: "1 Color available",
      price: 140,
    },
    {
      id: 5,
      img: "/images/preview1.png",
      name: "Nike Air Jordan5",
      category: "Men Shoes",
      color: "1 Color available",
      price: 150,
    },
  ],
};
